- ag-qs-sched.html
resetting schedule back to normal
> Work flow v2

- ag-qs-sched.html
> Cancelled Piano zoom session 11/9

- ag-qs-sched.html
> Lha sched updates

- ag-qs-sched.html
made two changes from monday.com form
> 11.16 updates

- iPrep-sp22.html
updated btn links and pushed updated page (iPrep-sp22) to sitefinity
> published iPrep page

- ag-qs-sched.html
> Edited time for comp. science for 12/14

- ag-qs-sched.html
Circuits and Electronics --> Objects oriented programming for Ravisher + Manharsh
> Engineering

- ag-qs-sched.html
added multiple sessions for chemistry (mayada) and business statistics (fatima) 
-Natalie
> Session Additions 

- ag-qs-sched.html
- au_sp22.html
Cross checked sessions with schedule. Added "Hosted by:" where applicable.
> In-Person Monday Sessions

- au_sp22.html
Special request from Zeyna to fix her title on the website :)
> Zeyna Aouad Description

- ag-qs-sched.html
Added additional in-person sessions for jennifer + rearranged to separate into physics I &II
> Separated physics I & II

- si.html
replaced old sessions with new sessions
> SI session schedule

- ag-qs-sched.html
Multiple reversions and moving of sessions to different days
> Updates 2/17

- sl-gen_a-sync.html
Completed embedding and formatting for Upload 3 Genetics Async
> Gen async  upload3

- ag-qs-sched.html
Philosophy zoom link updated, Accounting zoom session removed, reversion of last week's cancellations
> Updates 3/7

- ag-qs-sched.html
> Updates for today

- ag-qs-sched.html
Added Aarti's monday ochem session. reverted cancellations from Monday.
> Updates 3/10

- ag-qs-sched.html
Cancelled Hunter's sessions for 3/29
> Hunter's sessions

- ag-qs-sched.html
Added session for hunter, removed old cancellations, added new cancellations for Karl
> Updates 4/20

- ssw.html
Updates to workshops for the summer; requested by tyson. Thanks!
> SSW Updates
